### ISSUE TITLE
BOM line items reordered

### ISSUE THREAD

**Issue by kevinb456** [kitspace/bom-builder#17]
When importing the Raspberry Pi Compute Module IO Board Revision: 3.0 BOM, the line items order didn't match the original BOM.

**Comment by kevinb456** [comment]
[https://www.raspberrypi.org/documentation/hardware/computemodule/designdata/rpi_DSGN_CMIO_3p0.zip](url)

**Comment by kasbah** [comment]
Fixed with https://github.com/kitspace/bom-builder/commit/42f33dc107dcf84d392d709cee5c3135cc710afc

**Comment by kasbah** [comment]
Seems this is still not fully fixed.

**Comment by kasbah** [comment]
I reopened this due to some confusion with the sheet numbering. I think it is fixed.
