### ISSUE TITLE
Wrong quantities added to supplier carts

### ISSUE THREAD

**Issue by kevinb456** [kitspace/bom-builder#26]
e.g. x6 of RS part 8202847, and x10 PCBs should add 60off+ to the cart, but only adds 50off. MOQ in units of 25off so would expect 75off to be added to cart.

**Comment by kasbah** [comment]
I swear I saw this when we were looking at the same screen, but I can't reproduce it now even when using the same computer and BOM you were using. Feel free to open if you can reproduce of course.

**Comment by kasbah** [comment]
Saw this again just now.

**Comment by kasbah** [comment]
I believe this was the same issue as #33. The error was causing varied mis-behaviour including this.
