### ISSUE TITLE
Create column for MFN

### ISSUE THREAD

**Issue by patcon** [kitspace/bom-builder#3]

**Comment by kasbah** [comment]
What do you mean? Manufacturer part numbers are just called part numbers but you can already have as many part number columns as you like. 

![image](https://user-images.githubusercontent.com/206854/48200165-33c45e80-e356-11e8-9b5e-3c6ebd7237df.png)

**Comment by patcon** [comment]
Ah sorry, this was a quick issue created when I saw MFN missing from [the output pasted from] the browser plugin. I made a bad assumption that the code was shared :)
