### ISSUE TITLE
Part suggestion issues

### ISSUE THREAD

**Issue by kevinb456** [kitspace/bom-builder#30]
Few found, listed below;

"CAP, CHIP, 3216, 47uF, 20%, 6.3V" didn't find any results suitable from Farnell, but if you search for the same categories/filters in Octopart as electrogrammer resolves this to, you get the one suitable one which I also found manually on Farnell.

"CAP, CHIP, 1005, 100nF, 10%, 6.3V" most suggestions were for 1608 (metric) case size, not 1005.

Sometimes got 10% tolerance suggestions instead of requested 20% - not sure if this is intelligently intentional, or an accident? May be OK if the former, but would be good to understand. Doesn't happen in other cases where we could also be intelligent e.g. returning "16V" parts when "10V" requested.

**Comment by kasbah** [comment]
Moved to  https://github.com/kitspace/partinfo/issues/5
