### ISSUE TITLE
Look at the references column to figure out the component type

### ISSUE THREAD

**Issue by kevinb456** [kitspace/bom-builder#35]
Recognise abbreviated value endings e.g. 'n' for 'nF'

For this, parser needs to know what type of part it is, base this on reference designator e.g. C10 is a capacitor so "100n" means "100nF".

Just work with passives: Resistors, Capacitors
Postfixes: M, k, m, u/μ, n, p, plus 'R' for resistors

**Comment by kevinb456** [comment]
Also, cope with the unit being used as the separator, e.g. "3k3" for a resistor means the same as 3.3k , and "4n7" for a capacitor means the same as 4.7n

**Comment by kasbah** [comment]
3k3 is already supported (test with electro-grammar)

I moved the others to https://github.com/kitspace/electro-grammar/issues/20

**Comment by kasbah** [comment]
Not sure how to address this, you can enter `C 100n` or  `capacitor 100n` and that's parsed correctly. We could do something clever with the references.

**Comment by kasbah** [comment]
If call this issue "look at the references column to figure out the component type" then we can also pull in `R1, 100` which is described here: https://github.com/kitspace/electro-grammar/issues/21

**Comment by kasbah** [comment]
closed with 673509ad137fe020722fea15bbbbf338300363b5
