### ISSUE TITLE
No quantaty column - windows only

### ISSUE THREAD

**Issue by goran-mahovlic** [kitspace/bom-builder#75]
On windows machine I added some parts then saved csv, then tried to import again and it just returns this error
I have tried firefox and chrome
On linux machine in firefox same file imports ok.

Maybe someone has idea why this is happening?

![no_q_column](https://user-images.githubusercontent.com/4248736/176423699-df9cc605-595f-4349-9730-6f1cc6c5483f.png)

**Comment by kasbah** [comment]
Hi Goran, there's indeed a bug which I have seen before when both of these things coincide:

- File has Unix\Linux line endings
- Importing this file on Windows

The easiest work-around for now, I believe, is to open the file in Libreoffice Calc/Excel on Windows and save it as another file.

**Comment by goran-mahovlic** [comment]
Hmm I did try that import data into empty sheet then export as csv.
Also even creating everything on windows - and then save then import does not work.
Maybe it is also something else beside line endings.
For some reason on my linux machine parts search is like 100x slower so I was thinking of doing this on windows as it instantly finds parts.

Now in file I have just \n as line end - do you know what should I have on linux?

**Comment by kasbah** [comment]
Can you attach the file please?

The difference in speed is more likely down to caching rather than windows vs linux. The first time it runs a particular search it queries octopart, after that it's cached on the server for 24 hours.

**Comment by goran-mahovlic** [comment]
Here is file exported on linux - so if you can check what is wrong.

[1-click-bom_linux.csv](https://github.com/kitspace/bom-builder/files/9010321/1-click-bom_linux.csv)

**Comment by goran-mahovlic** [comment]
> The difference in speed is more likely down to caching rather than windows vs linux. The first time it runs a particular search it queries octopart, after that it's cached on the server for 24 hours.

Oh I see, I have tried other parts and yes it seams I just got lucky and got something out of cache, but if the speed is te same I can continue on linux :)

**Comment by kasbah** [comment]
I did manage to reproduce the issue and still believe it's a problem with line-endings. Here  it is converted to Excel which does import fine on Windows as well: [1-click-bom_linux.xlsx](https://github.com/kitspace/bom-builder/files/9010408/1-click-bom_linux.xlsx). Anyway, yeah, stick to Linux if you can :)

(Re: speed, in a few weeks Aisler may provide us with a solution to speed everything up!)

**Comment by goran-mahovlic** [comment]
> I did manage to reproduce the issue and still believe it's a problem with line-endings. Here it is converted to Excel which does import fine on Windows as well: [1-click-bom_linux.xlsx](https://github.com/kitspace/bom-builder/files/9010408/1-click-bom_linux.xlsx).

Your file works on my Windows machine, tnx  :)
 
>> Anyway, yeah, stick to Linux if you can :)

Yup I am on Linux 99% but still that 1% remains :)

> (Re: speed, in a few weeks Aisler may provide us with a solution to speed everything up!)

That sounds exciting!

I am closing this issue...

**Comment by kasbah** [comment]
I think the server just went down unfortunately. I'll let you know when it's back up.

**Comment by kasbah** [comment]
It's back up now.
